---
name: testing


on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  run_test:
    strategy:
      matrix:
        version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
          # - '3.7'
          # - '3.8'
          # - '3.9'
          # - '3.10'
          # - '3.11'

    runs-on:
      - ubuntu-latest

    container: python:${{ matrix.version }}-bookworm

    steps:
      - run: echo "${{ vars.PYTHON_VERSIONS }}"

      - run: python --version
